# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_colab/',
                'doc_host': 'https://muellerzr.github.io',
                'git_url': 'https://github.com/muellerzr/nbdev_colab/tree/master/',
                'lib_path': 'nbdev_colab'},
  'syms': { 'nbdev_colab.core': { 'nbdev_colab.core.git_push': ('core.html#git_push', 'nbdev_colab/core.py'),
                                  'nbdev_colab.core.setup_drive': ('core.html#setup_drive', 'nbdev_colab/core.py'),
                                  'nbdev_colab.core.setup_git': ('core.html#setup_git', 'nbdev_colab/core.py')},
            'nbdev_colab.modules': {'nbdev_colab.modules.foo': ('modules.html#foo', 'nbdev_colab/modules.py')}}}
