# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_modules.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/01_modules.ipynb 8
from .core import *

# %% ../nbs/01_modules.ipynb 10
def foo(a, b):
  "Returns the sum"
  return a+b
